### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by thedeepestreality** [makeevmr/Homework_s1#1]
А если b == 0? :)

https://github.com/makeevmr/Homework_s1/blob/c72ffbf775522cc5b9642be772ab11662054c31b/Homework%201/Task%202/quad_solve.cpp#L33

**Comment by makeevmr** [comment]
Добавил проверку условия b == 0 и c == 0
https://github.com/makeevmr/Homework_s1/blob/810fd392e0819fd40cb579e02208a917775308c0/Homework%201/Task%202/quad_solve.cpp#L33
