### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by thedeepestreality** [makeevmr/Homework_s1#2]
Чисто стилистически: я бы тут каждое условие завернул в отдельные скобки, чтобы выделить их из выражения, а само это выражение сразу можно будет вернуть через return, эффект будет тот же, а кода меньше. Но это все вкусовщина, конечно, кому-то проще читать с явной проверкой через if.

https://github.com/makeevmr/Homework_s1/blob/c72ffbf775522cc5b9642be772ab11662054c31b/Homework%201/Task%203/ring.cpp#L5

**Comment by makeevmr** [comment]
Добавил указанные изменения
https://github.com/makeevmr/Homework_s1/blob/810fd392e0819fd40cb579e02208a917775308c0/Homework%201/Task%203/ring.cpp#L5
